### ISSUE TITLE
git: Create auto gitImplementation

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/pkg#333]
Flux supports two git implementations: `libgit2` and `go-git`. They do not have feature parity, which the two main problems being:
- **Shallow clones** is only supported by `go-git`. Which results in less data being transmitted through the network at every clone operation.
- **Git V2 Protocol** is only supported by `libgit2`. Servers that only support this protocol (e.g. Azure DevOps) won't work with `go-git`.

We should build a third git implementation type (a.k.a `auto`), which removes the need from users to understand the difference between the implementations, and always try to use whichever is the most optimal.

On a high-level, the new implementation could take into account:
- Server fingerprint: query the SSH banner and HTTP headers.
- Protocol Awareness: find ways to identify what Git protocol version is being used, which may be easier over HTTP scheme.

**Comment by aryan9600** [comment]
I think we should close this issue as we have removed the `libgit2` git implementation from both source-controller and image-automation-controller.

**Comment by pjbgf** [comment]
Agreed, closing it. :+1:
