### ISSUE TITLE
Use reconcile annotation helpers in controllers

### ISSUE THREAD

**Issue by squaremo** [fluxcd/pkg#39]
For each project that uses the reconcileAt annotation:

 - bump its version of pkg/runtime to 0.1.2 (this picks up the new Changed predicate):

```sh
go get github.com/fluxcd/pkg/runtime@v0.1.2
```

 - ensure api/go.mod also has pkg/apis/meta v0.1.0 (this means you can use the status struct embed), with a similar `go get`
 - remove the `LastHandledReconcileAt` field from status and embed meta.ReconcileRequestStatus inline, instead:

```yaml
type ThingStatus struct {
    // ...
    meta.ReconcileRequestStatus `json:",inline"`
}
```

 - run `make manifests` to update the CRD; it should not alter the schema, only a doc string
 - run `make api-docs` (if there is one) to update docs. This does make a material change.
 - if there's anywhere that refers to `something.GetAnnotation()[meta.ReconcileAtAnnotation]`, change it to use `meta.ReconcileAnnotationValue(something.GetAnnotations())`
 - change `something.Status.LastHandledReconcileAt` to `something.Status.GetLastHandledReconcileRequest()`, and `something.Status.LastHandledReconcileAt = now` to `something.Status.SetLastHandledReconcileRequest(now)`

Projects:

 - [x] image-reflector-controller -- https://github.com/fluxcd/image-reflector-controller/pull/34 uses the helpers
 - [x] ~image-automation-controller~ (does not use reconcileAt, yet)
 - [x] kustomize-controller (https://github.com/fluxcd/kustomize-controller/pull/152)
 - [x] ~source-controller~ does not support reconcileAt or suspend
 - [x] helm-controller (https://github.com/fluxcd/helm-controller/pull/124)

Finally:

Once all of those have been updated and a minor version released, think about changing the annotation used by the command-line tool and the notification-controller, which both write the annotation. (EDIT: I think updating the CLI should wait for a minor version release, since it's a minor breaking change in the sense that the new CLI won't work with older controllers.)

**Comment by stefanprodan** [comment]
This was solved
