### ISSUE TITLE
ssa: ResourceManager.ApplyAll fails to apply ClusterRoleBinding

### ISSUE THREAD

**Issue by aerfio** [fluxcd/pkg#417]
We've got 2 controllers inside 1 operator (kubebuilder setup) that:
1. create some structs using client-go's https://github.com/kubernetes/client-go/tree/master/applyconfigurations. Among those resources is ClusterRole and ClusterRoleBinding
2. convert them to *unstructured.Unstructured using "k8s.io/apimachinery/pkg/runtime".DefaultUnstructuredConverter.ToUnstructured
3. uses ssa.SetNativeKindsDefaults on list of those resources
4. tries to apply them using ResourceManager.ApplyAll

There are some clusters for which this operation fails, like k8s@v1.24.4+rke2r1 and kind cluster created by kind@v0.17, default image for this version so k8s@1.25.3. They fail with error message
```json
{
	  "level": "error",
	  "ts": 1668516799.8819587,
	  "msg": "Reconciler error",
	  ...
	  "error": "failed to apply resources to the cluster: ClusterRoleBinding/crbName namespace not specified, error: clusterroles.rbac.authorization.k8s.io \"crName\" not found"
}
```
A bit of debugging led me to believe that the error comes from this line https://github.com/fluxcd/pkg/blob/7741c5ff7c8a25aca88269aa73111a3164724f95/ssa/manager_apply.go#L139 which then goes through `m.validationError(dryRunObject, err)` and then gets returned here https://github.com/fluxcd/pkg/blob/7741c5ff7c8a25aca88269aa73111a3164724f95/ssa/manager_diff.go#L184-L186

I'm not really sure what's happening, I'll try to add some code in next comment that reproduces this issue.

We've encountered this problem twice, independently in my workplace. For now we've just changed usage of ResourceManager.ApplyAll to for loop that goes through slice of those resources, which we additionally sort using [ssa.SortableUnstructureds](https://github.com/fluxcd/pkg/blob/7741c5ff7c8a25aca88269aa73111a3164724f95/ssa/sort.go#L67), and apply them using `ResourceManager.Apply`.

Resource manager is created like that:
```go
fieldManager:="some-string"
...
ResourceManager: ssa.NewResourceManager(mgr.GetClient(),
			nil, // poller is needed only for WaitForSet, we're not using it here
			ssa.Owner{
				Field: fieldManager,
				Group: fieldManager + "-group",
			}),
...
```

This seems like some kind of data-race, where ClusterRole is not yet fully "commited" and ClusterRoleBinding tries to reference no-yet-existing ClusterRole, but if I understand k8s it shouldn't happen 🙈. Weird this is that this error is not going away, subsequent reconciles do not succeed.

My setup:
- kind@v0.17, k8s 1.25.3
- go 1.19.3
- os: macos, intel based

**Comment by aerfio** [comment]
Ok, I've not been able to reproduce it for now... I might try again later

**Comment by stefanprodan** [comment]
We do test `ClusterRole/ClusterRoleBinding` see https://github.com/fluxcd/pkg/blob/main/ssa/testdata/test1.yaml

I suspect this is a RKE bug, not much we can do about it in this repo.

**Comment by aerfio** [comment]
@stefanprodan RKE is 1 thing, but it also bugs on kind, which is commonly used for e2e testing. Does it seem like a bug in ssa library, or should I look harder into controller-runtime's client? Wdyt?

**Comment by stefanprodan** [comment]
Flux itself contains `ClusterRole/ClusterRoleBinding` resources which are applied with `pkg/ssa`, and all our e2e tests use Kubernetes Kind. No one reported this bug nor did we see it in e2e tests, I would expect thousands of Flux users running into this issue.

**Comment by aerfio** [comment]
Sure, seems reasonable. Thanks for help 🙇🏻

**Comment by stefanprodan** [comment]
If you can consistently reproduce this with `kubectl apply --server-side --dry-run` against Kind, then this is an upstream bug, so the Kubernetes repo would be the best place to report it.

**Comment by hiddeco** [comment]
Closing this as it does not seem related to the actual package.
