### ISSUE TITLE
Export patching logic from SSA package

### ISSUE THREAD

**Issue by mclarke47** [fluxcd/pkg#439]
I'd love to use the SSA logic in a script I have, specifically [ssa/patch.go](https://github.com/fluxcd/pkg/blob/main/ssa/patch.go).
At least until similar logic is added to k8s.

Would it be possible to export these methods?

**Comment by stefanprodan** [comment]
@mclarke47 can you say more about your needs around this? Are you planning on using these functions without `ssa.Apply`?

**Comment by mclarke47** [comment]
I am planning on using them without `ssa.Apply` I'm using the dynamic client Appyl method and ran into https://github.com/kubernetes/kubernetes/issues/99003. I found the patch logic in flux to work really well and solve some issues I was having with client side applied objects.
