### ISSUE TITLE
Move MergeMaps to pkg

### ISSUE THREAD

**Issue by arbourd** [fluxcd/pkg#84]
As per https://github.com/fluxcd/flux2/blob/v0.8.0/internal/utils/utils.go#L403-L404, `MergeMaps` should be abstracted and moved to pkg.

What / where would be a good place for this function?

It will most likely be used by:
- flux2
- helm-controller
- source-controller

**Comment by hiddeco** [comment]
When moving, the version from helm-controller should be used as this one is the most complete with regard to comments and origin reference.

**Comment by arbourd** [comment]
I can update the transitive dependencies once this is released in runtime 😁

**Comment by hiddeco** [comment]
@arbourd made available in `v0.8.2`, thank you! :sunflower:
