### ISSUE TITLE
Send Elastic Common Schema Compliant Logs

### ISSUE THREAD

**Issue by sagargulabani** [fluxcd/pkg#95]
Our EKS cluster runs flux aside a lot of other services that are sending logs in ECS Compliant format. 
We face an issue where in because flux sends errors in `text` format, we are not able to ingest our service logs into Elasticsearch if a flux error log has already been ingested.
This is because [ECS Compliant Error logs](https://www.elastic.co/guide/en/ecs/current/ecs-error.html) expect the error field to be an object. Once the mapping for an index has been set by a flux error log to be text, and other type for that field will result in an error while ingestion.

It would be nice to get an option to use Elastic Common Schema format for the logs.

Thanks.

**Comment by stefanprodan** [comment]
> We face an issue where in because flux sends errors in text format

Flux v2 logs are in JSON format and the error is a dedicated object. My guess is that you're using Flux v1 which is deprecated.

**Comment by sagargulabani** [comment]
We are using the kustomize-controller v0.5.2. and this is what we get for the error field.
This is the name of our container image `
ghcr.io/fluxcd/kustomize-controller:v0.5.2
`
<img width="825" alt="Screenshot 2021-04-09 at 4 25 37 PM" src="https://user-images.githubusercontent.com/7789813/114170220-39bc3080-9950-11eb-9962-dfd6793fd6fe.png">

**Comment by stefanprodan** [comment]
Yes this is how Kubernetes controller-runtime formats the logs.

**Comment by sagargulabani** [comment]
yes, so the error field is a string, and it would be nice to have an option to configure the zap logger to conform to the [Elastic Log Schema](https://www.elastic.co/guide/en/ecs/current/index.html)

**Comment by stefanprodan** [comment]
Do you know any Kubernetes controller built with controller-runtime that does this?

**Comment by stefanprodan** [comment]
I'm looking at the controllers made by AWS here https://github.com/aws-controllers-k8s and none of them diverge from the standard controller-runtime log formatting.

**Comment by sagargulabani** [comment]
I am not aware of any Kubernetes controller built with controller runtime that does this.

A simple option could be to wrap the the core of the logger returned by runtime controller with the Elastic Common Schema Core at this [point](https://github.com/fluxcd/pkg/blob/196a3bafdbd5deb5e41cf81c94f4d21d2de5b1b1/runtime/logger/logger.go#L84) which can be controlled by a flag.
